### ISSUE TITLE
I'm trying to use barba.js through CDN but cannot connect...

### ISSUE THREAD

**Issue by m4th3w561** [barbajs/barba#662] opened 2022-01-17 15:40 UTC
This is my first time using barba.js and I'm developing a website with HTML CSS and JS. I'm trying to use the barba.js through the provided CDN in barba.js.org (<script src="https://unpkg.com/@barba/core"></script>) But I cannot connect somehow...
my browser  tells me this error:

DevTools failed to load source map: Could not load content for https://unpkg.com/@barba/barba.umd.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

need help

... 
    <script src="assets/gsap.min.js"></script>
    <script src="https://unpkg.com/@barba/core"></script>
    <script src="app.js"></script>
</body>

</html>

**Comment by xavierfoucrier** [comment] 2022-01-17 15:46
Duplicate of #558.

The provided CDN version works fine on my side.
https://unpkg.com/@barba/core@2.9.7/dist/barba.umd.js

> Raw source map URL for the UMD version is:
> https://unpkg.com/@barba/core@2.9.7/dist/barba.umd.js.map

**Closed by xavierfoucrier** 2022-01-17 15:46 UTC
Labels: duplicate

**Comment by m4th3w561** [comment] 2022-01-18 14:35
thank you @xavierfoucrier

**Comment by xavierfoucrier** [comment] 2024-01-04 11:26
> See https://github.com/barbajs/barba/issues/728.
