### ISSUE TITLE
Get paramater gets removed from url since 2.5

### ISSUE THREAD

**Issue by AndZyk** [barbajs/barba#448] opened 2019-09-26 08:35 UTC
## The problem

I have a search form and when I submit this form with the method "get", a new page loads with the "get" parameter in the url. Barba removes the get-parameter from the url since version 2.5.

### Details

For example I have this url:

```
http://example.com/page?q=Something
```

### Expected behaviour

The get parameter should stay after the page load:

```
http://example.com/page?q=Something
```

### Actual behaviour

The get parameter gets removed after the page load:

```
http://example.com/page
```

### Code To Reproduce Issue

This happens with just:

```js
barba.init();
```

### Steps to reproduce issue

* Install Barba.js version 2.5 or greater
* Initialize Barba.js
* Submit form with method "get"

Regards, Andreas

**Comment by Mamboleoo** [comment] 2019-09-26 09:11
It may be linked to those commented functions?
https://github.com/barbajs/barba/blob/ab9b7e617062b17c0a23f3b2eb526a2c2a2e7691/packages/core/src/utils/url.ts#L52

**Comment by xavierfoucrier** [comment] 2019-09-26 09:53
Hi everyone,

This is a duplicate of #445. Thanks for reporting the issue.

**Closed by xavierfoucrier** 2019-09-26 09:53 UTC
Labels: duplicate
