### ISSUE TITLE
Chrome tab discard give unexpected behavior

### ISSUE THREAD

**Issue by 1ucay** [barbajs/barba#530] opened 2020-06-04 18:46 UTC
Hello, I have issue with Chrome function Auto Tab Discard.
I have page, where Im using code like this
```
<?php if ( !isset( $_SERVER['HTTP_X_BARBA'] ) ) : ?>
<?php echo head(); /* THERE IS <html><head>CSS and JS... */ ?>
<?php else: ?>
<html>
    <head>
        <title><?php echo title(); ?></title>
    </head>
    <body>
<?php endif; ?>
<main data-ajax="container" data-ajax-namespace="home">
test content
</main>
<?php if ( !isset( $_SERVER['HTTP_X_BARBA'] ) ) : ?>
<footer></footer>
<?php endif; ?>
    </body>
</html>
```
Barba.js + barba/css works ok. Chrome suspend this tab (I have low performance computer). After that I switched back to this tab => page is reload without CSS JS in header. It return "cache" version of page like send again with HTTP_X_BARBA. You can test via Chrome "[chrome://discards/](url)"
**This is happend after click to link (after barba.js place new content with transition).**

Thank you

**Comment by thierrymichel** [comment] 2020-06-05 14:14
Hi @1ucay,

Would be great to have some reproductible code to be able to test it locally (and easily).
Thanks in advance.

FYI, you can send the whole HTML, no need to if / else (except saving a few bytes)

**Comment by xavierfoucrier** [comment] 2020-06-13 12:38
Hi @1ucay,

I already encountered a similar issue when using [Barba partial output](https://barba.js.org/docs/advanced/recipes/#Partial-output). If you just navigate on the first page, the HTML source will contain everything needed to display the website, like styles, resources, etc.. But if you navigate to another page, the source will only contain the page content without part you excluded: that's why, when coming back to the page, Chrome will only restore cached page instead of the entire source.

> As mentioned by Thierry, thanks for giving a minimal reproductible test repository.

**Comment by xavierfoucrier** [comment] 2020-07-14 13:05
Hi @1ucay,

Any update?

**Comment by xavierfoucrier** [comment] 2020-08-06 21:15
Any update since more than one month.
We will open it again if other users face this behavior.

Closing the issue.

**Closed by xavierfoucrier** 2020-08-06 21:15 UTC
Labels: await test repository, discussion
