### ISSUE TITLE
Simple transition example?

### ISSUE THREAD

**Issue by oueryemchi** [barbajs/barba#451] opened 2019-09-29 22:35 UTC
Hi there,

There is not one simple example of a transition in V2, and I am struggling to make it work at all.

Can anyone show me an example, please? thanks

**Comment by Moucky** [comment] 2019-09-30 01:58
#440

**Comment by xavierfoucrier** [comment] 2019-09-30 07:52
@oueryemchi duplicate of #440, closing the issue.

**Closed by xavierfoucrier** 2019-09-30 07:52 UTC
Labels: duplicate
