### ISSUE TITLE
Current container position on back button click

### ISSUE THREAD

**Issue by theamnesic** [barbajs/barba#557] opened 2020-09-02 17:25 UTC
Hi!

When I click on the back button of the browser, the scroll top position of the current container change (randomly?), and I can't find why.

I'm using a very simple transition to test it : 

```
.fade-leave
.fade-once-to
.fade-enter-to
  opacity 1

.fade-enter,
.fade-once,
.fade-leave-to
  opacity 0

.fade-leave-active,
.fade-once-active,
.fade-enter-active
  transition opacity 200ms ease
```

Any idea ?
Thanks!

**Comment by xavierfoucrier** [comment] 2020-09-07 10:20
Hi @theamnesic,

Are you talking about `@barba/css` plugin issue?
Thanks

**Comment by theamnesic** [comment] 2020-09-07 14:59
Hi Xavier, 

I have the same behavior without `@barba/css`.
This scroll top move only appear on the back button.

Here a [screenshot](https://www.dropbox.com/s/z18mz7d4it9lo1w/untitled.mov?dl=0), you can see the container 
Look like barba keep the previous scrollTop position even if we set to 0 at `enter`.

— G

**Comment by xavierfoucrier** [comment] 2020-09-07 20:26
Ho ok!

I wasn't figure it out ^^

Can you check this comment and tell me if it works for you?
https://github.com/barbajs/barba/issues/537#issuecomment-658160045.

Thanks!

**Comment by theamnesic** [comment] 2020-09-16 15:44
It works!

Just put this on `enter` hook : 

```js
if ('scrollRestoration' in history) {
  history.scrollRestoration = 'manual';
}
```

Merci Xavier !

**Comment by xavierfoucrier** [comment] 2020-09-17 07:56
De rien @theamnesic :wink: 
Happy coding with Barba!

I am closing the issue.

**Closed by xavierfoucrier** 2020-09-17 07:56 UTC
Labels: question

**Comment by xavierfoucrier** [comment] 2020-09-28 22:58
Duplicate of #537.
