### ISSUE TITLE
Barba with Wordpress Divi theme

### ISSUE THREAD

**Issue by tjpicasso** [barbajs/barba#607] opened 2021-03-02 02:21 UTC
Hi,

I am finding it really difficult to integrate barba with Divi theme. Is there a good documentation particular to this. I think the transition is working but the page is not loading images and grid

**Comment by xavierfoucrier** [comment] 2021-03-15 12:10
Hi @tjpicasso,

Sorry for the late reply, I am quite busy this past few weeks.
I am not familiar with Divi on WordPress, and I guess there is some things that won't work when using it on the front-end side.

I guess you should think on Barba as an "additional layout", and disable it when using Divi.
Can you explain a little bit more what kind of issues you are experiencing and how you are facing this issues?

Thanks a lot!

**Comment by StevenStavrakis** [comment] 2021-05-06 21:08
@tjpicasso I have been trying to get a good integration going for WordPress sites for a few weeks now. Most of them are just too heavy on custom css and js in their header and footer to use Barba effectively. Supposedly this will be fixed in a future update.

It may be possible to use it with Divi out of the box, but I would be surprised if that were the case.

**Comment by ofekN** [comment] 2021-06-28 19:18
> @tjpicasso I have been trying to get a good integration going for WordPress sites for a few weeks now. Most of them are just too heavy on custom css and js in their header and footer to use Barba effectively. Supposedly this will be fixed in a future update.
> 
> It may be possible to use it with Divi out of the box, but I would be surprised if that were the case.

Hey Steven did you try to solved with change index of your barba transition/container ? Maybe with assign high zindex with js after the doc is loaded, i've integrate barba for my past clients on few wp theme.
If the problem is where to put the code you can use wp plugins that provide js/css/html files and transform them into shortcode

**Comment by StevenStavrakis** [comment] 2021-06-28 19:27
> > @tjpicasso I have been trying to get a good integration going for WordPress sites for a few weeks now. Most of them are just too heavy on custom css and js in their header and footer to use Barba effectively. Supposedly this will be fixed in a future update.
> > It may be possible to use it with Divi out of the box, but I would be surprised if that were the case.
> 
> Hey Steven did you try to solved with higher z index of your barba transition/container ? Maybe with assign high z index with js after the doc is loaded, i've integrate barba for my past clients on few wp theme.
> If the problem is where to put the code you can use wp plugins that provide js/css/html files and transform them into shortcode

The problem I experienced during my attempts is that any given theme will have custom JS and CSS that it loads in the page headers. Supposedly Barba is going to be updated with the ability to update the header automatically. A manual solution would just be too much work to be worth it as far as I can tell.

**Comment by xavierfoucrier** [comment] 2021-06-29 07:27
@StevenStavrakis Yes in fact, as of today, Barba doesn't offer a way to reload css/js that are loaded in the header/footer when navigating between pages.

This will be the case with the `@barba/head` plugin, see https://barba.js.org/docs/plugins/head/.
Thanks everyone for your patience :wink:

**Closed by xavierfoucrier** 2021-06-29 07:27 UTC
Labels: question
