### ISSUE TITLE
Memory usage increase after ten pages or more

### ISSUE THREAD

**Issue by okikio** [barbajs/barba#571] opened 2020-10-03 22:22 UTC
I was curious as to how using Barba vs React deals with memory. I found that memory usage increased over time and never went back down.

I tested this effect on the barba js site, as well as [alessandroromagnoliph.it](https://www.alessandroromagnoliph.it/en) and a couple other sites; the problem seems to be that the caching system barba uses doesn't clear old pages after a certain point in time.

I would expect after a certain number of page barba would start clearing the cache.
What happens instead is that ram usage compounds the more page you go to. 

To reproduce this issue, go to the barba js site and [alessandroromagnoliph.it](https://www.alessandroromagnoliph.it/en), but I am pretty all sites that use barba js suffer from this.

I used the new Chromium Edge v85.0.564.63, for my testing but my suspicions indicate that the cache doesn't clear pages.

**Comment by xavierfoucrier** [comment] 2020-10-04 12:23
Hi @okikio,

Thanks for opening the issue.
Please provide a **minimum reproductible test repository** for that specific case.

Regards :wink:

**Comment by okikio** [comment] 2020-10-10 23:30
@xavierfoucrier 

Sorry, it's taken me, so, long here is the repo [github.com/okikio/web-app/tree/barba](https://github.com/okikio/web-app/tree/barba), I created a Github Pages for the repo: [okikio.github.io/web-app/](https://okikio.github.io/web-app/).

I used an old project. It's on the `barba` branch.

**Comment by xavierfoucrier** [comment] 2020-10-12 14:54
Hi @okikio,

Thanks for the repo.
I will take a look shortly and give a feedback here :wink:

**Comment by xavierfoucrier** [comment] 2020-10-15 12:50
Hi @okikio,

Thanks for taking time to give a minimal test repository.

Unfortunately, after a bunch of tests, it looks like there is nothing related to Barba... it's more about how your code is managed. As you are calling a `_load()` method after the Barba transition finished, you are adding new event listeners that may increase memory usage. Here is some kind of "critical call" from my point of view: https://github.com/okikio/web-app/blob/barba/src/js/app.js#L111.

Be sure to properly clean/remove unused event listeners when navigating between your pages, and not add new listeners on elements who already have.

Closing the issue :wink:

**Closed by xavierfoucrier** 2020-10-15 12:50 UTC
Labels: question
