### ISSUE TITLE
DevTools failed to load SourceMap: Could not load content for https://unpkg.com/@barba/barba.umd.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### ISSUE THREAD

**Issue by auliamnaufal** [barbajs/barba#566] opened 2020-09-23 09:36 UTC
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Barba).

Tell us what you were trying to do and what happened instead.

Remember, this is _not_ a place to ask questions. For that, get your invite to [https://barbajs.slack.com](https://join.slack.com/t/barbajs/shared_invite/enQtNTU3NTAyMjkxMzAyLTkxYWUwZmM1YWQxMmNlYmE0ZjY4NDQxMGUxYjkwYWFlMzEzOWM4OTRhMWRmYTQyYzFlMmQ3OGFmYmI3MWY0OWY)!

### Details

If necessary, describe the problem you have been experiencing in more detail.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Code To Reproduce Issue [ Good To Have ]

```js
// Avoid posting hundreds of lines of source code.
// Edit to just the relevant portions.
```

### Steps to reproduce issue [ Good To Have ]

Tell us how to reproduce this issue. Please provide a working demo, you can use this template as a base.

---

## Relevant Links

- If your project is public, link to the repo so we can investigate directly.
- **BONUS POINTS:** Create a [minimal reproduction](http://stackoverflow.com/help/mcve) and upload it to GitHub. This will get you the fastest support.

## Environment

- Barba version that exhibits the issue:
- Build used:
  - [x] module (esm/)
  - [x] browser (dist/)
  - [ ] main (lib/)
- Browser OS/version used:

**Comment by xavierfoucrier** [comment] 2020-09-23 09:39
Hi @auliamnaufal,

It's a duplicate of #554.
Closing the issue.

**Closed by xavierfoucrier** 2020-09-23 09:39 UTC
Labels: duplicate
