### ISSUE TITLE
Checkboxes not working, and external links are not redirected

### ISSUE THREAD

**Issue by essetcheizee** [barbajs/barba#747] opened 2024-08-05 12:21 UTC
### What version are you using?

2.10.2

### What package are you using?

@barba/core

### Describe your issue

Checkboxes suddenly doesn't work when removing barba.init() it works properly, also the external links are not go to the URL intended. It does not simply work at all.

**Comment by jamie-humm** [comment] 2024-08-05 12:35
Also have this issue with checkboxes. Reverting to 2.9.7 works for now.

**Comment by maguati** [comment] 2024-08-05 15:27
Same issue here. After debugging i noticed that even with default barba the checkboxes are not working.

**Comment by xavierfoucrier** [comment] 2024-08-06 11:31
Duplicate of #746.
Closing the issue.

**Closed by xavierfoucrier** 2024-08-06 11:31 UTC
Labels: bug, duplicate
