### ISSUE TITLE
Help! All of my a href https link won't open

### ISSUE THREAD

**Issue by HafidYusuf** [barbajs/barba#749] opened 2024-08-07 04:59 UTC
### What version are you using?

v2.10.2

### What package are you using?

@barba/core

### Describe your issue

I've made my website portfolio and it works fine a few months ago... and suddenly all of my external links won't open, you guys can check it here: [https://hafidyusuf.com/](https://hafidyusuf.com/)

this is the code [https://github.com/HafidYusuf/HafidYusuf](https://github.com/HafidYusuf/HafidYusuf)

there is no problem for every link to the own website page, but every link that goes outside of the website won't work, can you help me on this please, thanks

**Comment by CraigTheNerd** [comment] 2024-08-07 13:05
I'm having the same issue, also using @barba/core v2.10.2 but the same issue exists on @barba/core v2.10.0

**Comment by HafidYusuf** [comment] 2024-08-07 13:58
For now I just add this in the bottom of my html code:
`
    <script>
        function openLink(link) {
            window.open(link, '_blank');
        }
    </script>
`
and this in every <a> tag
`<a onclick="openLink('https://linkedin.com/')" href="https://linkedin.com/" target="_blank">Linked In</a>`

**Comment by zvassos** [comment] 2024-08-07 17:51
@HafidYusuf made a small function untill this is fixed might work for you too!

`document.querySelectorAll('a[target="_blank"]').forEach(externalLink => {
        externalLink.addEventListener('click', function(){
            window.open(externalLink.getAttribute('href'), '_blank', 'noopener, noreferrer');
        })
    })`

**Comment by dkrnl** [comment] 2024-08-08 06:21
same issues

**Comment by xavierfoucrier** [comment] 2024-08-08 12:47
Duplicate of https://github.com/barbajs/barba/issues/746.
Closing the issue.

**Closed by xavierfoucrier** 2024-08-08 12:47 UTC
Labels: bug, duplicate
