### ISSUE TITLE
Page reload if clicking on an active menu

### ISSUE THREAD

**Issue by HoloBack** [barbajs/barba#556] opened 2020-08-27 12:49 UTC
Hi everyone,

first of all thanks a lot for this great piece of software :) it's great to work with.
I'm not sure if it's an issue or if it's wanted - if I open f.e. the contact page (or any other page) by clicking on the navigation item, Barba does it's job and it opens via transitions. If I click a second time on the currently active navigation item, it then opens with a regular page load. Is there any reason for this behaviour?

**Comment by xavierfoucrier** [comment] 2020-08-30 23:11
Hi @HoloBack,

This is the intended behavior.
It's a duplicate of https://github.com/barbajs/barba/issues/132.

> If you need to custom this behavior, use the `prevent` strategy here:
> https://barba.js.org/docs/advanced/strategies/#prevent

**Closed by xavierfoucrier** 2020-08-30 23:11 UTC
Labels: duplicate
