### ISSUE TITLE
imagesLoaded and page transitioning with barba js

### ISSUE THREAD

**Issue by akabei** [barbajs/barba#413] opened 2019-07-01 09:55 UTC
Hello there!
I need to integrate imagesLoaded.js with barba.js but I can't achieve it. I'm trying to load all the images (backgrounds too) in the "beforeEnter" view hook, waiting for them with a promise and proceed with the "enter" transition hook.

For some reason the "enter" transition hook fires before the "beforeEnter" view hook.

What am I doing wrong? Are transitions and views not linked? Thanks in advance.

My code:
```
barba.init({
transitions: [{
        leave: function (data) {
            return new Promise(resolve => {
                anime({
                    before: function () {
                        body.classList.add('transitioning');
                    },
                    complete: function () {
                        resolve();
                    },
                    duration: 500,
                    easing: 'easeInOutQuad',
                    targets: loader,
                    translateX: ['-100%', '0%']
                });
            });
        },

        enter: function (data) {
            anime({
                complete: function () {
                    body.classList.remove('transitioning');
                },
                duration: 500,
                easing: 'easeInOutQuad',
                targets: loader,
                translateX: ['0%', '100%']
            });
        }
    }],

views: [{
        namespace: 'home',

        afterLeave: function (data) {
            ...
        },

        beforeEnter: function (data) {
            ...

            return new Promise(resolve => {
                imagesLoaded(data.next.container.querySelector('.main'), {background: true}, function () {
                    resolve();
                });
            });
        }
    }]
});
```

**Comment by luruke** [comment] 2019-07-02 13:29
Hello @akabei ,
I believe the issue is that, Views callbacks are not "waiting" for promises.

<img width="607" alt="Screenshot 2019-07-02 at 15 28 22" src="https://user-images.githubusercontent.com/61326/60516437-0dd13d00-9cde-11e9-95db-7bf6a93f2aa5.png">
<img width="453" alt="Screenshot 2019-07-02 at 15 28 17" src="https://user-images.githubusercontent.com/61326/60516439-0e69d380-9cde-11e9-8e05-f4fc65179953.png">

appear/leave/enter are the only methods (in transition) that accepts promises.

Does that helps you?
If not, do you have a live link?

**Comment by akabei** [comment] 2019-07-02 14:07
Thanks @luruke for the reply and your great work.
What i would like to achieve is:
Transition out -> initialize my logic in the data.next.container and wait for all images -> transition in.

There is no way to get it? Should I load images in the transition? Is it logically correct?

I have a live dev protected area.

**Comment by luruke** [comment] 2019-07-02 14:14
@akabei I guess it's up to you if you want to have this loading logic in the `transition` or as a "on-boarding animation/behaviour" for a single page.

It also depends how (and if) you are planning to re-use your transition.

Stupid example:
- Homepage with text + video + images

Do you want to display the homepage just if the images are loaded?

**Comment by akabei** [comment] 2019-07-02 14:30
I used the namespace 'home', but it is a default view that will executes in every page transition.

> Do you want to display the homepage just if the images are loaded?

Exactly, I'm trying to understand if there is a way to do it.

**Comment by luruke** [comment] 2019-07-02 14:36
Maybe you just need a generic component independent from transition / views.

In the agency we built a microframework to handle those kind of things, doing that we don't even use the `Views`, but generic components that fires methods when entering / leaving the DOM.

See https://github.com/thierrymichel/kapla

I'm closing this as isn't really related to a bug, feel free to jump on the slack channel if you have more questions

**Closed** 2019-07-02 14:37 UTC
